[supervisord]
nodaemon=true

[program:fastapi]
command=uvicorn insurance_premium_api:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true

[program:streamlit]
command=streamlit run UI.py --server.address=0.0.0.0 --server.port 10000
autostart=true
autorestart=true
